pipeline:
    name: Progressive Rollout
    identifier: Progressive_Rollout
    projectIdentifier: FF_Demo
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Enable Flag
              identifier: Enable_Flag
              description: ""
              type: FeatureFlag
              spec:
                  execution:
                      steps:
                          - step:
                                type: FlagConfiguration
                                name: Rollout Builds Module
                                identifier: Rollout_Builds_Module
                                spec:
                                    feature: Builds_Module
                                    environment: dev
                                    instructions:
                                        - identifier: AddRuleIdentifier
                                          type: AddRule
                                          spec:
                                              priority: 100
                                              distribution:
                                                  clauses:
                                                      - op: segmentMatch
                                                        attribute: ""
                                                        values:
                                                            - Harness_Users
                                                  variations:
                                                      - variation: "true"
                                                        weight: 50
                                                      - variation: "false"
                                                        weight: 50
                                                  bucketBy: identifier
                                timeout: 10m
